"""Import full photography albums as web-ready WebP files.

Usage:
    python scripts/import_albums.py "C:/path/to/source/assets"
"""

from __future__ import annotations

import json
import shutil
import sys
from pathlib import Path

from PIL import Image, ImageOps


ALBUMS = {
    "wedding": "Wedding",
    "prewedding": "Prewedding",
    "events": "Events",
}
IMAGE_EXTENSIONS = {".jpg", ".jpeg", ".png", ".webp", ".avif"}
MAX_SIZE = (1800, 1800)


def import_album(source: Path, output: Path, public_name: str) -> list[str]:
    files = sorted(
        (path for path in source.rglob("*") if path.is_file() and path.suffix.lower() in IMAGE_EXTENSIONS),
        key=lambda path: str(path.relative_to(source)).casefold(),
    )

    shutil.rmtree(output, ignore_errors=True)
    output.mkdir(parents=True, exist_ok=True)
    imported: list[str] = []

    for index, source_image in enumerate(files, start=1):
        filename = f"{public_name}-{index:03d}.webp"
        destination = output / filename
        try:
            with Image.open(source_image) as image:
                image = ImageOps.exif_transpose(image)
                image.thumbnail(MAX_SIZE, Image.Resampling.LANCZOS)
                if image.mode not in ("RGB", "RGBA"):
                    image = image.convert("RGB")
                image.save(destination, "WEBP", quality=84, method=4)
            imported.append(f"/albums/{public_name}/{filename}")
            print(f"[{public_name}] {index}/{len(files)} {source_image.name}", flush=True)
        except Exception as error:  # Keep importing if one source file is damaged.
            print(f"[{public_name}] skipped {source_image}: {error}", file=sys.stderr, flush=True)

    return imported


def write_manifest(manifest_path: Path, albums: dict[str, list[str]]) -> None:
    lines = [
        "/** Generated by scripts/import_albums.py. */",
        "export const ALBUM_IMAGES = {",
    ]
    for key, images in albums.items():
        lines.append(f"  {key}: {json.dumps(images, ensure_ascii=False)},")
    lines.extend(["} as const;", ""])
    manifest_path.write_text("\n".join(lines), encoding="utf-8")


def main() -> None:
    if len(sys.argv) != 2:
        raise SystemExit("Pass the source assets directory as the only argument.")

    project_root = Path(__file__).resolve().parents[1]
    source_root = Path(sys.argv[1]).expanduser().resolve()
    public_root = project_root / "public" / "albums"
    manifest: dict[str, list[str]] = {}

    for key, source_folder in ALBUMS.items():
        source = source_root / source_folder
        if not source.is_dir():
            raise SystemExit(f"Missing album folder: {source}")
        manifest[key] = import_album(source, public_root / key, key)

    write_manifest(project_root / "lib" / "albumAssets.ts", manifest)
    print(
        "Imported "
        + ", ".join(f"{key}: {len(images)}" for key, images in manifest.items()),
        flush=True,
    )


if __name__ == "__main__":
    main()
